# Generated by Django 3.2.3 on 2021-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooksmodel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=None),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=None),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=None),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=None),
        ),
    ]
